trigger:
- dev/4.0.0

pool:
  vmImage: vs2017-win2016

variables:
  buildConfiguration: Release
  buildPlatform: Any CPU
  solution: '.\src\Caliburn.Micro.sln'

steps:
- task: VSBuild@1
  displayName: Nuget Restore
  inputs:
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Restore'

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/t:Build'

- task: VSTest@2
  displayName: Run Unit Tests
  inputs:
    testAssemblyVer2: '.\bin\**\*.Tests.dll'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'
