trigger:
- dev/4.0.0

pool:
  vmImage: vs2017-win2016

variables:
  buildConfiguration: Release
  buildPlatform: Any CPU
  solution: 'src\Caliburn.Micro.sln'

steps:
- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool
  
- script: nbgv cloud
  displayName: Set Version

- task: VSBuild@1
  displayName: Nuget Restore
  inputs:
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Restore'

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/t:Build'

- task: VSTest@2
  displayName: Run Unit Tests
  inputs:
    testAssemblyVer2: 'bin\**\*.Tests.dll'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'

- task: CopyFiles@2
  displayName: Copy Packages to Artifact Directory
  inputs:
    Contents: 'packages\*.nupkg'
    TargetFolder: '$(build.artifactStagingDirectory)\packages'

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)\packages'
    artifactName: Packages