trigger:
- dev/4.0.0

pool:
  vmImage: vs2017-win2016

variables:
  buildConfiguration: Release
  solution: './src/Caliburn.Micro.sln'

steps:
- task: VSBuild@1
  displayName: Nuget Restore
  inputs:
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Restore'

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Build'